var cards = [
  { name: "alejandro",        img:  "alejandro.jpg",   answer: [0, 1]},
  { name: "alfredo",        img:  "alfredo.jpg",   answer: [1,2]},
  { name: "ana",       img:  "ana.jpg",   answer: [0,3,4]},
  { name: "anita",     img:  "anita.jpg",   answer: [5,6,13]},
  { name: "bernardo",      img:  "bernardo.jpg",   answer: [7,8,10]},
  { name: "carlos",       img:  "carlos.jpg",   answer: [1,5]},
  { name: "clara",      img:  "clara.jpg",   answer: [2,9,10]},
  { name: "david",       img:  "david.jpg",   answer: [5,11]},
  { name: "ernesto",      img:  "ernesto.jpg",   answer: [5,10]},
  { name: "felipe",       img:  "felipe.jpg",   answer: [0,3,11,13]},
  { name: "german",       img:  "german.jpg",   answer: [2,12]},
  { name: "guillermo",       img:  "guillermo.jpg",   answer: [2,12,13]},
  { name: "jorge",      img:  "jorge.jpg",   answer: [7,10,14]},
  { name: "manuel",    img:  "manuel.jpg",   answer: [1,3,8]},
  { name: "maria",     img:  "maria.jpg",   answer: [8,10]},
  { name: "pablo",  img:  "pablo.jpg",   answer: [9,14]},
  { name: "paco",  img:  "paco.jpg",   answer: [2,3]},
  { name: "pedro",  img:  "pedro.jpg",   answer: [14]},
  { name: "pepe", img:  "pepe.jpg",   answer: [3,5,9]},
  { name: "ricardo",     img:  "ricardo.jpg",   answer: [1,8,11,12]},
  { name: "roberto",  img:  "roberto.jpg",   answer: [8,13]},
  { name: "samuel",  img:  "samuel.jpg",   answer: [9,12,14]},
  { name: "susana", img:  "susana.jpg",   answer: [13,14]},
  { name: "tomas",img:  "tomas.jpg",   answer: [0,9,12]},
];

var questions = [ "Es moren@?",
                  "Tiene bigote?",
                  "Es peliroj@?",
                  "Tiene el pelo rizado?",
                  "Usa pendientes?",
                  "Es rubi@?",
                  "Tiene coleta?",
                  "Lleva sombrero?",
                  "Es castañ@?",
                  "Tiene gafas?",
                  "Lleva sombrero?",
                  "Tiene barba?",
                  "Es calvo?",
                  "Tiene chapetas?",
                  "Tiene el pelo blanco?"
                ];