var cards = [
  { name: "gabi",   img:  "gabi.png",     answer: [1,11,15,16]},
  { name: "susana", img:  "susana.png",   answer: [6,11,15]},
  { name: "ismael", img:  "ismael.png",   answer: [3,14]},
  { name: "diego",  img:  "diego.png",    answer: [1,4,8]},
  { name: "ale",    img:  "ale.png",      answer: [5,13]},
  { name: "vero",   img:  "vero.png",     answer: [13,16]},
  { name: "sarai",  img:  "sarai.png",    answer: [6,13]},
  { name: "david",  img:  "david.png",    answer: [1,2,4]},
  { name: "sandra", img:  "sandra.png",   answer: [5,8,16]},
  { name: "victor", img:  "victor.png",   answer: [6,10]},
  { name: "minyu",  img:  "minyu.png",    answer: [9,13]},
  { name: "dunnia", img:  "dunnia.png",   answer: [0,5,9]},
  { name: "quique", img:  "quique.png",   answer: [0,13]},
  { name: "anna",   img:  "anna.png",     answer: [5,14]},
  { name: "giorgio",img:  "giorgio.png",  answer: [1,4,7,11,15]},
  { name: "juan",   img:  "juan.png",     answer: [11,15,16]},
  { name: "abel",   img:  "abel.png",     answer: [3,16]},
  { name: "marc",   img:  "marc.png",     answer: [12,15,16]},
  { name: "jesus",  img:  "jesus.png",    answer: [1,4,16]},
  { name: "miguel", img:  "miguel.png",   answer: [2,4,9,10]},
  { name: "niko",   img:  "niko.png",     answer: [2,14]},
  { name: "laura",  img:  "laura.png",    answer: [7,13]},
  { name: "andres", img:  "andres.png",   answer: [10,16]},
  { name: "beltran",img:  "beltran.png",  answer: [11,13,15]},
];

var questions = [ "¿Lleva bufanda?",
                  "¿Tiene barba?",
                  "¿Lleva nariz de pachacho?",
                  "¿Es calvo?",
                  "¿Tiene bigote?",
                  "¿Tiene el pelo largo?",
                  "¿Tiene el pelo rizado?",
                  "¿Su foto es en B/N?",
                  "¿Lleva collar?",
                  "¿Tiene flequillo?",
                  "¿Su foto es de perfil?",
                  "¿Es TA?",
                  "¿Piensa que hay muchos Pablos en clase?",
                  "¿Lleva gorro o sombrero?",
                  "¿Gasta pajarita?",
                  "¿Es profe?",
                  "¿Lleva gafas?"
                ];